Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,62 +71,58 @@ jobs:
           file_glob: true
           overwrite: true
 
-      - name: Update changelog and Magisk update json
-        id: update_config
-        run: |
-          git checkout -f update || git switch --discard-changes --orphan update
-          cp -f build.tmp build.md
-          get_update_json() {
-            echo "{
-            \"version\": \"$1\",
-            \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }},
-            \"zipUrl\": \"$2\",
-            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
-          }"
-          }
-
-          cd build || { echo "build folder not found"; exit 1; }
-          for OUTPUT in *magisk*.zip; do
-            [ "$OUTPUT" = "*magisk*.zip" ] && continue
-            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
-            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
-            UPDATE_JSON="${UPDATE_JSON##*/}"
-            VER=$(echo "$ZIP_S" | grep version=)
-            VER="${VER##*=}"
-            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
-            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
-          done
-          cd ..
-
-          find . -name "*-update.json" | grep . || : >dummy-update.json
-
-      - uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-          branch: update
-          skip_checkout: true
-          file_pattern: build.md *-update.json
-          commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
+#      - name: Update changelog and Magisk update json
+#        id: update_config
+#        run: |
+#          git checkout -f update || git switch --discard-changes --orphan update
+#          cp -f build.tmp build.md
+#          get_update_json() {
+#            echo "{
+#            \"version\": \"$1\",
+#            \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }},
+#            \"zipUrl\": \"$2\",
+#            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
+#          }"
+#          }
+#
+#          cd build || { echo "build folder not found"; exit 1; }
+#          for OUTPUT in *magisk*.zip; do
+#            [ "$OUTPUT" = "*magisk*.zip" ] && continue
+#            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+#            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then continue; fi
+#            UPDATE_JSON="${UPDATE_JSON##*/}"
+#            VER=$(echo "$ZIP_S" | grep version=)
+#            VER="${VER##*=}"
+#            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+#            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+#          done
+#          cd ..
+#
+#          find . -name "*-update.json" | grep . || : >dummy-update.json
+#
+#      - uses: stefanzweifel/git-auto-commit-action@v5
+#        with:
+#          branch: update
+#          skip_checkout: true
+#          file_pattern: build.md *-update.json
+#          commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
 
       - name: Report to Telegram
         env:
           TG_TOKEN: ${{ secrets.TG_TOKEN }}
-        if: env.TG_TOKEN != null
+          TG_CHAT: ${{ secrets.TG_CHAT }}
+        if: ${{ env.TG_TOKEN != null && env.TG_CHAT != null }}
         run: |
           cd build || { echo "build folder not found"; exit 1; }
 
-          TG_CHAT="@rvc_magisk"
           NL=$'\n'
           APKS=""
-          MODULES=""
           for OUTPUT in *; do
             DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
             if [[ $OUTPUT = *.apk ]]; then
               APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
-            elif [[ $OUTPUT = *.zip ]]; then
-              MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
             fi
           done
-          MODULES=${MODULES#"$NL"}
           APKS=${APKS#"$NL"}
 
           BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d;' ../build.md)"
@@ -135,9 +131,6 @@ jobs:
           ${BODY}
 
           *▼ Download Links:*
-          Modules:
-          ${MODULES}
-
           APKs:
           ${APKS}
           "
